name: .NET
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore Steve.Merkle/Steve.Merkle.sln
    - name: Build
      run: dotnet build Steve.Merkle/Steve.Merkle.sln --configuration Release
    - name: Test
      run: dotnet test Steve.Merkle/Steve.Merkle.sln --configuration Release --verbosity normal